CREATE TABLE IF NOT EXISTS hive_record (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR(255),
  file_key VARCHAR(512),
  zipped BOOLEAN,
  provider VARCHAR(32),
  bucket_name VARCHAR(128),
  storage_class_cache VARCHAR(32),
  size BIGINT,
  update_time TIMESTAMP,
  status VARCHAR(32),
  last_sync_time TIMESTAMP,
  deletable BOOLEAN,
  deleted BOOLEAN DEFAULT FALSE,
  restore_time TIMESTAMP,
  download_status VARCHAR(32)
);

CREATE TABLE IF NOT EXISTS file_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255),
  storage_class VARCHAR(16) NOT NULL DEFAULT 'STANDARD',
  bucket_name VARCHAR(128),
  preview_policy VARCHAR(32) NOT NULL DEFAULT 'DEFAULT',
  ui_variant VARCHAR(32) NOT NULL DEFAULT 'hot',
  is_system BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_file_category_code ON file_category(code);
CREATE UNIQUE INDEX IF NOT EXISTS uk_file_category_bucket ON file_category(bucket_name);

CREATE TABLE IF NOT EXISTS file_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  group_code VARCHAR(64) NOT NULL,
  group_name VARCHAR(128) NOT NULL,
  group_desc VARCHAR(255),
  sort_order INT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_group_category FOREIGN KEY (category_id) REFERENCES file_category(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_group_cat_code ON file_group(category_id, group_code);
CREATE INDEX IF NOT EXISTS idx_group_cat_sort ON file_group(category_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_group_enabled ON file_group(enabled);

CREATE TABLE IF NOT EXISTS file_group_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  hive_record_id INT NOT NULL,
  assigned_by VARCHAR(64),
  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_fgr_group FOREIGN KEY (group_id) REFERENCES file_group(id),
  CONSTRAINT fk_fgr_record FOREIGN KEY (hive_record_id) REFERENCES hive_record(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_group_record ON file_group_record(group_id, hive_record_id);
CREATE INDEX IF NOT EXISTS idx_record_group ON file_group_record(hive_record_id, group_id);

CREATE TABLE IF NOT EXISTS hive_record_image_meta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hive_record_id INT NOT NULL UNIQUE,
  thumb_key VARCHAR(512),
  thumb_status VARCHAR(32),
  image_width INT,
  image_height INT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_image_meta_record FOREIGN KEY (hive_record_id) REFERENCES hive_record(id) ON DELETE CASCADE
);
